### ISSUE TITLE
keeping passThru global css out of the globalCssModule

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#209]
Opening a broader issue in favor of reopening #207 

#### Synopsis

We do want some global/functional css classes for consumer usage. The reactstrap components attempt to map to cssModule keys, and pass thru if one is not found. This works great, until an inadvertent global selector is included in the cssModule without being wrapped in `:global`. 

#### TODO

* [ ] Have an explicit strategy for dealing with this. Removing global cssModule keys at run time just before usage in `setGlobalCssModule` is not very nice and will be bug-prone.
* [ ] Vet the general "path of least privilege" override usage (fix in `core` vs `reactstrap` vs `components` vs `create a new scoped module`)
* [ ] Get a consensus with contributors this is a good model

**Comment by eckdanny-osi** [comment]
this topic was resolved in #196 and #214. closing.
