### ISSUE TITLE
Improve the DX of the CaresProvider component

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#330]
Its awkward. This became clear in https://github.com/ca-cwds/dashboard/pull/144

The provider should have a better interface. It should be clearly documented with examples

### TODO

* [ ] Surface the `IconButtonDropdown` component
* [ ] Use the `IconButtonDropdown` in the ContextProvider default for `UserMenu`
* [ ] export a component that wraps children in the Provider instead of exporting the raw Provider itself 

related: #305
